cabal-version: 3.0
name: nix-x-cabal-utils
version: 0.1.0.0
license: BSD-3-Clause
license-file: LICENSE
author: bgl gwyng
maintainer: bgl@gwyng.com
build-type: Simple
extra-doc-files: CHANGELOG.md

common warnings
  ghc-options:
    -Wall
    -Wunused-packages

common dependencies
  build-depends:
    base ^>=4.20.2.0

common language
  default-language: GHC2024
  default-extensions:
    BlockArguments
    DuplicateRecordFields
    OverloadedRecordDot
    RecordWildCards

library
  import: warnings, language, dependencies
  hs-source-dirs: lib
  exposed-modules:
    NixXCabal.NixOutput
    NixXCabal.Output
    NixXCabal.PackageSet
    NixXCabal.PackagesConfig
    NixXCabal.ReposConfig
    NixXCabal.Repository
    NixXCabal.Resolve

  build-depends:
    Cabal,
    Cabal-syntax,
    aeson,
    bytestring,
    cabal-install,
    cabal-install-solver,
    cabal2nix,
    containers,
    directory,
    distribution-nixpkgs,
    filepath,
    hackage-security,
    language-nix,
    lens,
    network-uri,
    tar,

executable generate-no-index-cache
  import: warnings, language, dependencies
  main-is: generate-no-index-cache.hs
  hs-source-dirs: exe

executable generate-secure-repo-index-cache
  import: warnings, language, dependencies
  main-is: generate-secure-repo-index-cache.hs
  hs-source-dirs: exe

executable generate-package-set
  import: warnings,  language, dependencies
  main-is: generate-package-set.hs
  hs-source-dirs: exe
  build-depends:
    Cabal,
    Cabal-syntax,
    aeson,
    base,
    bytestring,
    cabal-install,
    containers,
    nix-x-cabal-utils,
    optparse-applicative,

executable generate-packages-nix
  import: warnings,  language, dependencies
  main-is: generate-packages-nix.hs
  hs-source-dirs: exe
  build-depends:
    Cabal-syntax,
    aeson,
    base,
    bytestring,
    containers,
    directory,
    filepath,
    nix-x-cabal-utils,
    optparse-applicative,
